package(default_visibility = ["//visibility:public"])

py_library(
    name = "basetest",
    testonly = 1,
    srcs = ["basetest.py"],
    deps = [
        "@absl_git//absl/testing:absltest",
    ],
)
