load("//upvote:builddefs.bzl", "py_appengine_library")

package(default_visibility = ["//upvote"])

py_appengine_library(
    name = "all",
    deps = [
        "//upvote/gae/shared/binary_health:all",
        "//upvote/gae/shared/common:all",
    ],
)
